### ISSUE TITLE
There was an error extracting the ZIP file, it is either corrupted or using an invalid format.

### ISSUE THREAD

**Issue by kevindaus** [xthiago/pdf-version-converter#11]
While installing in windows 10 machine , 
I installed ghostscript and added it to PATH environment variable but still this error . 
"There was an error extracting the ZIP file, it is either corrupted or using an invalid format."

heres the screenshot : https://imgur.com/a/f3vxZ

**Comment by nh-mike** [comment]
I also have this problem, a month later, on Windows 7 x64. I have cleared my composer cache and still, it refuses to extract.

**Comment by xthiago** [comment]
The issue seems related to the test file `Sp3ci4l"; <'Ch4r5'> !£$%&()=?^[]{}è@#§.pdf`. Maybe `composer` or `git` are having a trouble to deal with the filename. 

We must investigate that.

**Comment by xthiago** [comment]
@nh-mike @kevindaus 

For now I removed the file `Sp3ci4l"; <'Ch4r5'> !£$%&()=?^[]{}è@#§.pdf`.

Can someone test the library on Windows and tell me if the issue was fixed?

In order to test you will need import the code of `dev-master`. (E.g. `composer require "xthiago/pdf-version-converter" "dev-master"`).

**Comment by Thavia** [comment]
Tested on Windows 10. It works! Thanks.

**Comment by xthiago** [comment]
@Thavia thank you!

I released a new version (`1.0.4`), so you can change it in your `composer.json` file.
